// client/src/components/main/TaggingBox.jsx
import React, { useState } from 'react';
import { useMutation } from '@apollo/react-hooks';
import gql from 'graphql-tag';
import PropTypes from 'prop-types';
import './TaggingBox.css';

const ASSIGN_TAG = gql`
  mutation tagFile($filePath: String, $tagName: String) {
    tagFile(filePath: $filePath, tagName: $tagName) {
      filePath,
      tagNames
    }
  }
`;
const UNASSIGN_TAG = gql`
 mutation untagFile($filePath: String, $tagName: String) {
   untagFile(filePath: $filePath, tagName: $tagName) {
     filePath,
     tagNames
   }
 }
`;

// const UPDATE_CACHE = gql`
//   query updateCache()
// `;
import { GET_TAGS } from './MetaDisplay';

export default function TaggingBox(
  { filePath, addTagForDisplay, removeDisplayedTag }
) {
  const [assignTag] = useMutation(ASSIGN_TAG);
  const [unassignTag] = useMutation(UNASSIGN_TAG);
  const [val, setVal] = useState('');

  function onAdd(inputString) {
    const name = inputString.trim();
    if (name.length) {
      assignTag({ variables: { filePath, tagName: name }, 
        refetchQueries: [{query: GET_TAGS, variables: { filePath } }] });
      addTagForDisplay(name);
    }
    setVal('');
    console.log('onAdd');
  }
  function onDelete(name) {
    unassignTag({ variables: { filePath, tagName: name },
      refetchQueries: [{query: GET_TAGS, variables: { filePath } }] });
    removeDisplayedTag(name);
    setVal('');
    console.log('onDelete()');
  }
  return (
    <div className='TaggingBox'>
      <input value={val}
        onChange={ (e) => setVal( e.target.value.toLowerCase() ) } 
      />
      <button onClick={ 
        () => { onAdd(val); } 
      }>
        {'+'}
      </button>
      <button onClick={
        () => { onDelete(val); }
      }
      >
        {'-'}
      </button>
    </div>
  );
}

TaggingBox.propTypes = {
  filePath: PropTypes.string,

  addTagForDisplay: PropTypes.func,
  removeDisplayedTag: PropTypes.func,
};

// newClient/src/components/main/TaggingBox.svelte
<script>
  import { getClient, mutate } from 'svelte-apollo';
  import { ASSIGN_TAG, UNASSIGN_TAG } from '../../queries.js';
  import { fileFocus, searchArray } from '../../stores.js';

  export let filePath; export let updateTags;
  let value = '';
  $: console.log(value);

  const client = getClient();
  async function assignTag(tagName) {
    try {
      await mutate(client, {
        mutation: ASSIGN_TAG,
        variables: { filePath, tagName }
      });
    } catch(error) { console.log('error! assignTag()'); }
  }
  async function unassignTag(tagName) {
    try {
      await mutate(client, {
        mutation: UNASSIGN_TAG,
        variables: { filePath, tagName }
      });
    } catch(error) { console.log('unassignTag() error!'); }
  }
  function onAdd(inputString) {
    const tagNames = inputString.split(',').map( t => t.trim() );
    console.log(tagNames);
    // if array has a first string with content
    if (tagNames.length && tagNames[0].length) {
      tagNames.forEach(tagName => {
        assignTag(tagName);
        console.log(tagName); updateTags();
      });
    }
    value = '';
  }
  function onDel(inputString) {
    unassignTag(inputString);
    value = ''; updateTags();
  }
  $: value = value.toLowerCase();
</script>

<div>
  <input bind:value />
  <button on:click={() => onAdd(value) }>Add</button>
  <button on:click={() => onDel(value)}>Del</button>
</div>

<style>
  div { display: flex; justify-content: space-around; }
</style>
