// client/src/components/footer/SubFolderSelector.jsx
import React, { useState, useEffect } from 'react';
import gql from 'graphql-tag';
import { useQuery } from '@apollo/react-hooks';

import useLogging from '../../tools/useLogging';
import useBoolWatch from '../../tools/useBoolWatch';

const GET_CHILD_FOLDERS = gql`
  query folderPathsInFolder($folderPath: String) {
    folder(folderPath: $folderPath) {
      folders {
        folderPath
      }
    }
  }
`;

export default function SubFolderSelector(props) {
  `Takes a folderPath and renders a dropdown 
  to select from the children`

  const { data, loading, error } = useQuery(GET_CHILD_FOLDERS,
    { variables: { folderPath: props.folderPath } }
  );
  const [subFolders, setSubFolders] = useState([]);
  useEffect(()=>{
    if (error) { throw error }
    else if (loading) { console.log('SubFolderSelector Loading...') }
    else {
      const folderPaths = [...data.folder.folders.map( folder => folder.folderPath ) ];
      console.log(folderPaths);
      const folders = new Map();
      folderPaths.forEach((folderPath) => {
        folders.set( folderPath.slice( folderPath.lastIndexOf('/') ), folderPath );
      });
      setSubFolders(folders);
    }
  },[data]);

  useLogging('subFolders', subFolders);
  const flag = useBoolWatch(subFolders);

  return flag ? (
    <select name="subfolders" id="SubFolderSelector">
    <option value="">subfolders</option>
    {Array.from(subFolders, ([folderName, folderPath])=>{
      return (
        <option key={folderPath} 
          value={folderPath}
          onClick={(e)=>{ props.setFolderFocus(folderPath) } }
        >
          {folderName}
        </option>
      );
    })}
    </select>
  ) : <p></p>;
};

// newClient/src/components/header/SubFolderSelector.svelte
<script>
  import { getClient, query } from 'svelte-apollo';
  import { GET_CHILD_FOLDERS } from '../../queries.js';
  import { folderFocus } from '../../stores.js';

  const client = getClient();
  const qData = query(client, { query: GET_CHILD_FOLDERS, 
    variables: { folderPath: $folderFocus } });
  $: qData.refetch({ folderPath: $folderFocus });
</script>

{#await $qData}
  <p>loading...</p>
{:then qResult}
  {#if qResult.data.folder.folders.length}
    <select name='subfolders'>
      <option disabled>subfolders</option>
      {#each qResult.data.folder.folders as folder}
        <option value={folder.folderPath} 
          on:click={ () => $folderFocus = folder.folderPath }>
          {folder.folderPath.slice(folder.folderPath.lastIndexOf('/') + 1)}
        </option>
      {/each}
    </select>
  {/if}
{:catch error}
  <p>error!</p>
{/await}
