// newClient/src/components/main/Slide.svelte
<script>
  import { getClient, query } from 'svelte-apollo';
  import spinner from '../../../assets/Spinner-1s-200px.gif';
  import warning from '../../../assets/warning.jpeg';
  import { GET_FILE } from '../../queries.js';
  export let filePath;
  const client = getClient();
  const qData = query(client, { query: GET_FILE, variables: {filePath} });
  $: qData.refetch({ filePath });
</script>

<div class=className>
  {#await $qData}
  <img src={spinner} alt='The image is being loaded...'
    class='system'
  />
  {:then qResult}
  <img src={ 'data:image/gif;base64,' + qResult.data.file.contents } 
    alt='Image fetched from graphql endpoint' 
  />
  {:catch error}
  <img src={warning} alt={error.message} class='system'/>
  {/await}
</div>

<style>
  div { display: flex; justify-content: space-around; }
  img.system { width: 24vw; } 
  img { cursor: pointer; }
</style>

// client/src/components/main/Slide.jsx
import React from 'react';
import { useQuery } from '@apollo/react-hooks';
import gql from 'graphql-tag';
import PropTypes from 'prop-types';
import spinner from '../../../assets/Spinner-1s-200px.gif';
import warning from '../../../assets/warning.jpeg';
import './Slide.css';

const GET_FILE = gql`
  query file($filePath: String) {
    file(filePath: $filePath) {
      contents
    }
  }
`;

export default function Slide({filePath, height, width}) {
  // const src = usePicture(filePath);
  const { data, loading, error } = useQuery(
    GET_FILE, { variables: { filePath } }
  );
  let src = loading ? spinner : warning;
  if (error) { console.log('Slide query error'); console.log(error); }
  if (data) { src = 'data:image/gif;base64,' + data.file.contents; }

  return (
    <div className='Slide'>
      <img src={src}
        alt={filePath} height={height} width={width} 
      />
    </div>
  );
}

Slide.propTypes = {
  filePath: PropTypes.string,
  height: PropTypes.number,
  width: PropTypes.number,
};
